# Generated by Django 5.0.6 on 2024-06-20 20:08

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjuntoURL', models.URLField()),
                ('descripcion', models.TextField()),
                ('fechaFin', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('institucionOtorgante', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enofilo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apellido', models.CharField(max_length=255)),
                ('imagenPerfil', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Maridaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NovedadEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDescuentoPremium', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('esSoloPremium', models.BooleanField()),
                ('fechaHoraEvento', models.DateTimeField()),
                ('nombreEvento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegionVitivinicola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CobroPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esAnual', models.BooleanField()),
                ('fechaPago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nroOperacionMercadoPago', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_premium', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincias', models.ManyToManyField(related_name='paises', to='bonvino.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='region_vitivinicola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='bonvino.regionvitivinicola'),
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadasUbicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('historia', models.TextField()),
                ('nombre', models.CharField(max_length=255)),
                ('periodoActualizacion', models.DateField()),
                ('region_vitivinicola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='bonvino.regionvitivinicola')),
            ],
        ),
        migrations.CreateModel(
            name='Siguiendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateField()),
                ('fechaInicio', models.DateField()),
                ('amigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido_por', to='bonvino.enofilo')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido_por', to='bonvino.bodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siguiendo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enofilo',
            name='amigos',
            field=models.ManyToManyField(related_name='seguidores', through='bonvino.Siguiendo', to='bonvino.enofilo'),
        ),
        migrations.CreateModel(
            name='Sommelier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fechaValidacion', models.DateField()),
                ('notaPresentacion', models.TextField()),
                ('certificaciones', models.ManyToManyField(related_name='sommeliers', to='bonvino.certificacion')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='siguiendo',
            name='sommelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguido_por', to='bonvino.sommelier'),
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('añada', models.CharField(max_length=255)),
                ('fechaActualizacion', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('notaDeCataBodega', models.TextField()),
                ('precioARS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinos', to='bonvino.bodega')),
                ('maridajes', models.ManyToManyField(related_name='vinos', to='bonvino.maridaje')),
            ],
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('porcentajeComposicion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_uva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonvino.tipouva')),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varietales', to='bonvino.vino')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('esPremium', models.BooleanField()),
                ('fechaReseña', models.DateField()),
                ('puntaje', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to=settings.AUTH_USER_MODEL)),
                ('vino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='bonvino.vino')),
            ],
        ),
        migrations.AddField(
            model_name='enofilo',
            name='favoritos',
            field=models.ManyToManyField(related_name='enofilos_favoritos', to='bonvino.vino'),
        ),
    ]
