# Generated by Django 5.0.6 on 2024-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonvino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='region_vitivinicola',
        ),
        migrations.AddField(
            model_name='provincia',
            name='region_vitivinicola',
            field=models.ManyToManyField(related_name='provincias', to='bonvino.regionvitivinicola'),
        ),
    ]
